version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www/html
            - ./logs:/var/log/app
        links:
            - php
    php:
        #image: "php:7.3-fpm"
        build: "./images/php"
        links:
            - redis
            - memcached
        volumes:
            - ./images/php/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
            - ./www:/var/www/html
            - ./logs:/var/log/app
    go:
        image: golang:latest
        volumes:
            - ./go:/go/app
        working_dir: /go/app
        ports:
            - "90:80"
        links:
            - redis
            - memcached
        environment:
            PORT: 80
        command: go run test/main.go
    mysql:
        #image: mysql:latest
        image: mariadb:latest
        ports:
            - "3306:3306"
        links:
            - adminer
        user: "1000"
        command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
        #command: '--default-authentication-plugin=mysql_native_password'
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
        restart: always
    pgsql:
        image: postgres:latest
        ports:
            - "5432:5432"
        links:
            - adminer
        volumes:
            - ./pgsql:/var/lib/postgresql
        environment:
            POSTGRES_PASSWORD: postgres
        restart: on-failure
    adminer:
        image: adminer:latest
        ports:
            - "8080:8080"
        restart: always
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - ./redis:/data
        restart: on-failure
    memcached:
        image: memcached
        ports:
            - "11211:11211"
        restart: on-failure
