version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www/html
            - ./logs:/var/log/app
        links:
            - php
    php:
        image: "php:7.3-fpm"
        #build: "./images/php"
        links:
            - mysql
            - pgsql
            - redis
            - memcached
        volumes:
            - ./images/php/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
            - ./www:/var/www/html
            - ./logs:/var/log/app
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: local
    pgsql:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - ./pgsql:/var/lib/postgresql
        environment:
            POSTGRES_PASSWORD: local
    adminer:
        image: adminer
        ports:
            - "8080:8080"
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - ./redis:/data
    memcached:
        image: memcached
        ports:
            - "11211:11211"
